### ISSUE TITLE
MarkerValue documentation suggestion

### ISSUE THREAD

**Issue by michaelkpdx** [aenhancers/after-effects-scripting-guide#1]
Hi,

Just curious if it would help others on the MarkerValue object documentation page ( [here](https://ae-scripting.docsforadobe.dev/other/markervalue/?highlight=markerproperty#markervalue-object) ) to show an example of getting and setting MarkerValues for a composition since that seems to be different than a layer. What do you think? I know there are some good examples at: https://ae-scripting.docsforadobe.dev/items/compitem/#compitem-markerproperty

Thanks,

Michael

**Comment by zlovatt** [comment]
The [CompItem.markerProperty](https://github.com/aenhancers/after-effects-scripting-guide/blob/master/docs/items/compitem.rst#compitemmarkerproperty) page already shows how to set comp markers :)

The syntax is identical between comp and layer markers, just that the object property differs between them (`CompItem.markerProperty` vs `Layer.marker`, for the object property shortcuts)

**Comment by michaelkpdx** [comment]
Hi zlovatt,

Thanks for the reply. I'm new here and maybe don't understand how it all works. I just recommended this because of my own experience where I've read through the documentation here and couldn't figure out why 

`var markerProperty = compItem.property("Marker");` 

wasn't working. The description for the MarkerValue object described that it "represents a layer or composition marker." But didn't hint that the object property would be different, so I assumed they were the same. Perhaps a note like, "See also: CompItem.markerProperty"

If I'm just oblivio, I understand. But just thought to suggest this if you think it would help other newbies like me.

**Comment by zlovatt** [comment]
Closing this!

Added in explicit examples on how to add in comp and layer markers to the MarkerValue page, as well as examples in both `CompItem.markerProperty` and `Layer.marker` headings. 

See 7d14db1

**Comment by michaelkpdx** [comment]
Cool. Btw, the documentation is such an amazing resource! Thank you soo much!
