### ISSUE TITLE
Add Keyframe Color Labels API

### ISSUE THREAD

**Issue by Klustre** [aenhancers/after-effects-scripting-guide#14]
### Property.keyLabel(`keyIndex`) 
Returns the `labelIndex` value assigned to the referenced keyframe as an integer. (0 for None, or 1 to 16 for one of the preset colors in the Labels preferences). 

Read only. 

### Property.setLabelAtKey(`keyIndex`, `labelIndex`) 
Sets the `labelIndex` value for the referenced keyframe. (0 for None, or 1 to 16 for one of the preset colors in the Labels preferences). 

No return value.
 
[Source](https://community.adobe.com/t5/after-effects-beta-discussions/updates-to-keyframe-color-labels/m-p/12941519#M2134)

**Comment by zlovatt** [comment]
Handled by @tkurkoskiAdobe
