### ISSUE TITLE
Missing fonts

### ISSUE THREAD

**Issue by andyglez96** [aenhancers/after-effects-scripting-guide#15]
Good afternoon, there is a way to obtain the missing fonts of a project using the script?

**Comment by Klustre** [comment]
Hi @andyglez96, you should ask in the [After Effects Forums](https://community.adobe.com/t5/after-effects/ct-p/ct-after-effects?page=1&sort=latest_replies&lang=all&tabid=all&topics=label-scripting). It's more likely you'll get an answer there. 

This repo's Github issues are reserved for actual issues with the documentation.
