### ISSUE TITLE
Something worng with docs

### ISSUE THREAD

**Issue by Yuelioi** [aenhancers/after-effects-scripting-guide#2]
https://ae-scripting.docsforadobe.dev/items/folderitem/#folderitem-item
source：app.project.item(index).item
maybe：app.project.item(index).item(index) ?

**Comment by zlovatt** [comment]
Fixed in f259ab7

**Comment by Yuelioi** [comment]
https://ae-scripting.docsforadobe.dev/layers/avlayer/#avlayer-blendingmode
In AVLayer.blendingMode section, it has two “BlendingMode.SUBTRACT”
