### ISSUE TITLE
Shapes are missing 'rotoBezier' property

### ISSUE THREAD

**Issue by blastframe** [aenhancers/after-effects-scripting-guide#21]
MaskPropertyGroup and Shape Path property groups can both use [rotoBezier interpolation](https://ae-scripting.docsforadobe.dev/properties/maskpropertygroup.html?highlight=rotoBezier#maskpropertygroup-rotobezier), however only MaskPropertyGroup are available through the API. Please make this property available for Shape Path groups.

<img width="284" alt="image" src="https://user-images.githubusercontent.com/3729547/226074275-27dbacbd-6ae0-4462-a769-7abe5686b4a3.png">

**Comment by Klustre** [comment]
We only document existing APIs. To request new APIs please make a post on the [Adobe Forums](https://community.adobe.com/t5/after-effects/ct-p/ct-after-effects?page=1&sort=latest_replies&filter=all&lang=all&tabid=ideas).
