### ISSUE TITLE
Bug/Request: Add link to ExtendScript types in descriptions

### ISSUE THREAD

**Issue by rafikhan** [aenhancers/after-effects-scripting-guide#8]
While reading the description of Project.file there is a reference to `ExtendScript File`. I would expect this to be clickable to the documentation of the type but it's not there like in other places.

![image](https://user-images.githubusercontent.com/40667/146296502-86d7899b-cd81-4611-808d-4c610186876c.png)

**Comment by Klustre** [comment]
It should point to the Extendscript docs:
https://extendscript.docsforadobe.dev/file-system-access/file-object.html#file-object-properties

We can probably drop the mention of Extendscript and just call it the `File` object.
